curl 'https://foreupsoftware.com/index.php/api/booking/users/reservations' \
  -H 'authority: foreupsoftware.com' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"' \
  -H 'x-newrelic-id: VwcGVVBVDBABVllXBAYPUVwE' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'accept: application/json, text/javascript, */*; q=0.01' \
  -H 'x-requested-with: XMLHttpRequest' \
  -H 'api-key: no_limits' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'origin: https://foreupsoftware.com' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://foreupsoftware.com/index.php/booking/20330/4502' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: PHPSESSID=ah3md0fo2hj4o5cdjt18rnktqj; _ga=GA1.2.1718378909.1640743795; _gid=GA1.2.83974600.1640743795; __stripe_mid=427dfb2a-29fa-48d9-aaf7-96ca9b35ebc88ab194; __stripe_sid=a4f286d5-bc72-42b6-8752-2e4c20a5c3a8c07be9; token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJhdWQiOiJmb3JldXBzb2Z0d2FyZS5jb20iLCJpYXQiOjE2NDA3NDUyNjMsImV4cCI6MTY0MzMzNzI2MywidWlkIjoiMjgzNDkyNDYiLCJsZXZlbCI6MCwiY2lkIjoiMjAzMzAiLCJlbXBsb3llZSI6ZmFsc2UsImlzX3Zpc2l0b3IiOnRydWV9.jX_vBhbQASEXr6ginyvTy8hvVEpoZs7FMwksGFL1oc9Wfw2Bf6vsTQMM3jFIMGucxv4Gcnns_rVTBYuuMDIgmg' \
  --data-raw '{"teesheet_id":"4502","teesheet_holes":"18","time":"2022-01-06 16:30","course_id":"20330","course_name":"Los Verdes Golf Course","schedule_name":"Los Verdes 1st Tee","schedule_id":"4502","available_spots":4,"minimum_players":2,"trade_min_players":8,"trade_available_players":0,"foreup_trade_discount_rate":0,"holes":18,"has_special":false,"special_discount_percentage":0,"group_id":false,"require_credit_card":1,"booking_class_id":3979,"booking_fee_required":false,"booking_fee_price":false,"booking_fee_per_person":false,"green_fee_tax_rate":false,"green_fee_tax":0,"guest_green_fee_tax_rate":false,"guest_green_fee_tax":0,"cart_fee_tax_rate":false,"cart_fee_tax":0,"guest_cart_fee_tax_rate":false,"guest_cart_fee_tax":0,"special_id":false,"foreup_discount":false,"pay_online":"no","green_fee":18,"cart_fee":12.5,"guest_green_fee":18,"guest_cart_fee":12.5,"rate_type":"both","players":4,"carts":false,"promo_code":"","promo_discount":0,"player_list":false,"duration":1,"hide_prices":false,"show_course_name":false,"min_players":2,"max_players":4,"notes":[],"customer_message":"","total":72,"purchased":false,"pay_players":4,"pay_carts":false,"pay_total":72,"pay_subtotal":72,"paid_player_count":0,"discount_percent":0,"discount":0,"details":"","pending_reservation_id":"$1","allow_mobile_checkin":0,"foreup_trade_discount_information":[],"airQuotesCart":[{"type":"item","description":"Green Fee","price":18,"quantity":4,"subtotal":72}],"preTaxSubtotal":72,"estimatedTax":0,"subtotal":72,"available_duration":null,"increment_amount":null,"credit_card_id":"1603535"}' \
  --compressed
